Added Docyard application as Not Vulnerable
NCSC-NL/log4shell pull request #457
Opened 2021-12-16 09:09 UTC by fransbloemen

Thank you for your contribution! Some pointers to get it merged quickly:

For contributions in `software/`:

  - Status: please select a value from the status table at the top
  - Version: Status Vulnerable / Workaround? -> List vulnerable versions.
             Status Fix?                     -> List fixed versions.
  - Links: make sure you link to a public statement by the developer.
    Alternatively, include and link a file in the `software/vendor-statements/`
    directory
  - Please mind the sorting
  - Please put vendor/product name in PR title (instead of "Update README.md")

2021-12-16 09:49 UTC, maertsen requested changes
hi @fransbloemen, thanks for your contribution. Can you take a look at my comments?

2021-12-16 09:49 UTC, maertsen commented on software/README.md
> +| Docuwork | DocYard | All Versions | Not Vuln | | [source](https://docuwork.nl) |
please provide a more specific source url; the homepage does not contain any log4j information at a first glance.

2021-12-16 09:49 UTC, maertsen commented on software/README.md
> -| Apache        | JSPWiki | 2.11.1 | Fix | |[source](https://jspwiki-wiki.apache.org/Wiki.jsp?page=Log4J-CVE-2021-44228) |
Can you restore this line?

2021-12-16 10:00 UTC, fransbloemen commented on software/README.md
> +| Docuwork | DocYard | All Versions | Not Vuln | | [source](https://docuwork.nl) |
We'll do that soon!

2021-12-16 10:00 UTC, fransbloemen commented on software/README.md
> -| Apache        | JSPWiki | 2.11.1 | Fix | |[source](https://jspwiki-wiki.apache.org/Wiki.jsp?page=Log4J-CVE-2021-44228) |
Done

2021-12-16 10:14 UTC, maertsen requested changes

2021-12-16 10:14 UTC, maertsen commented on software/README.md
> +| Docuwork | DocYard | All Versions | Not Vuln | | [source](https://docuwork.nl) |
I would prefer a more stable url than the homepage, say a direct link to a news item. I'll merge once your provide one.

2021-12-17 12:33 UTC, maertsen commented
hi @fransbloemen, I'm closing this PR for lack of response. Feel free to reopen one when you have an updated url for us.

2021-12-17 12:33 UTC, closed without merging