Updated WebSphere Application Server with 2nd fix PH42762
NCSC-NL/log4shell pull request #657
Opened 2021-12-19 13:14 UTC by hubje2020

Thank you for your contribution! Some pointers to get it merged quickly:

For contributions in `software/`:

  - [ ] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
  - [ ] Status: please select a value from the status table at the top
  - [ ] Version: Status Vulnerable / Workaround? -> List vulnerable versions.
             Status Fix?                     -> List fixed versions.
  - [ ] Links: make sure you link to a public statement by the developer.
    Alternatively, include and link a file in the `software/vendor-statements/`
    directory
  - [ ] Please mind the sorting

2021-12-19 16:27 UTC, grayum commented
Thanks for the PR. However due to several conflicts could you please fetch, rebase and fix the branch before you send an update PR. This is probably due to an old local repo.

2021-12-20 13:28 UTC, grayum commented
We've added new columns in regards to added CVE's. Please fetch, update accordingly and issue a new PR. Thank you.

2021-12-21 13:41 UTC, maertsen requested changes
These are the minimal changes required to merge @hubje2020. Any updates from your side are appreciated.

2021-12-21 13:41 UTC, maertsen commented on software/README.md
> +| IBM | WebSphere | 8.5 | Vulnerable | fix: PH42728, PH42762 | [source](https://www.ibm.com/support/pages/node/6525706/), [source](https://www.ibm.com/support/pages/node/6526750)|
```suggestion
| IBM | WebSphere | 8.5 | | Workaround | Workaround | | apply hotfixes PH42728, PH42762 | [source](https://www.ibm.com/support/pages/node/6525706/), [source](https://www.ibm.com/support/pages/node/6526750)|
```

2021-12-21 13:41 UTC, maertsen commented on software/README.md
> +| IBM | WebSphere | 9.0 | Vulnerable | fix: PH42728, PH42762 | [source](https://www.ibm.com/support/pages/node/6525706/), [source](https://www.ibm.com/support/pages/node/6526750)|
```suggestion
| IBM | WebSphere | 9.0 | | Workaround | Workaround | | apply hotfixes PH42728, PH42762 | [source](https://www.ibm.com/support/pages/node/6525706/), [source](https://www.ibm.com/support/pages/node/6526750)|
```

2021-12-21 13:41 UTC, maertsen commented on software/README.md
> +| IBM | Business Automation Workflow | 18.0.0+ | Fix | JR64456 / JR64096 | [source](https://www.ibm.com/support/pages/node/6525834)|
```suggestion
| IBM | Business Automation Workflow | 18.0.0+ |  | Workaround |  |  | apply JR64456 / JR64096 | [source](https://www.ibm.com/support/pages/node/6525834)|
```

2021-12-24 08:57 UTC, grayum commented
No updated PR in 5 days. Closing this one.

2021-12-24 08:57 UTC, closed without merging