Added Personio to Readme
NCSC-NL/log4shell pull request #674
Opened 2021-12-20 09:40 UTC by leisemann

Added Personio (HR Tool) to Readme

2021-12-20 13:30 UTC, grayum commented
We've added new columns to add other relevant CVE's. Please fetch, update accordingly and issue a new PR. Thank you.

2021-12-21 13:31 UTC, maertsen requested changes
@leisemann, we can merge when you apply the suggested change.

2021-12-21 13:31 UTC, maertsen commented on software/README.md
> +| Personio | All | Unknown |  | Fix | Investigation | | [source](https://status.personio.de/incidents/kn4c6mf6lpdv) |
```suggestion
| Personio | All | Unknown |  | Fix | Investigation | | | [source](https://status.personio.de/incidents/kn4c6mf6lpdv) |
```

If you have any additional information about the status of the other CVE, that'd be helpful.

2021-12-21 15:30 UTC, merged

2021-12-21 15:30 UTC, maertsen commented
thanks @leisemann