Added DocVue Software
NCSC-NL/log4shell pull request #718
Opened 2021-12-21 15:28 UTC by Securenetology

Added DocVue Software. Fix for CVE-2021-4104

Thank you for your contribution! Some pointers to get it merged quickly:

For contributions in `software/`:

  - [ ] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
  - [ ] Status: please select a value from the status table at the top
  - [ ] Version: Status Vulnerable / Workaround? -> List vulnerable versions.
             Status Fix?                     -> List fixed versions.
  - [ ] Links: make sure you link to a public statement by the developer.
    Alternatively, include and link a file in the `software/vendor-statements/`
    directory
  - [ ] Please mind the sorting

2021-12-21 15:32 UTC, maertsen requested changes
hi @Securenetology, thanks for contributing to the software list. Can you have a look at my comments? Some changes are necessary before we can merge.

2021-12-21 15:32 UTC, maertsen commented on software/README.md
> +| Docvue | Docvue Client Agent | fix | Unknown | Unknown | Unknown | Unknown | New client package can be retrieved from support. | |
- Can you provide a software version in the `version` column?
  - Can you put _Fix_ in the columns that match the respective CVE?
  - Can you provide an url to a vendor statement?

2021-12-21 16:00 UTC, Securenetology commented on software/README.md
> +| Docvue | Docvue Client Agent | fix | Unknown | Unknown | Unknown | Unknown | New client package can be retrieved from support. | |
Like this? Sorry I'm new at this.

| Docvue | Docvue Client Agent | <11.1.6.10447 | fix | Unknown | Unknown | Unknown | Unknown | New client package can be retrieved from support. | [source] https://user-images.githubusercontent.com/89155495/146959966-a3d39148-0b76-44a4-8418-5e91fa40ca2a.png |

2021-12-21 16:34 UTC, tschmidtb51 commented on software/README.md
> +| Docvue | Docvue Client Agent | fix | Unknown | Unknown | Unknown | Unknown | New client package can be retrieved from support. | |
No worries. We are here to help you: Let's do that step by step:
1. Is `11.1.6.10447` the first fixed version? If so, just remove `<` upfront.
2. Which one of the 4 vulnerability is addressed by that patch?
  
    |Status CVE-2021-4104 | Status CVE-2021-44228 | Status CVE-2021-45046 | Status CVE-2021-45105|
    |-- | -- | -- | --|
  
    Put into the corresponding column a _Fix_, leave other empty. (I couldn't find out from the statement you linked, but maybe you have more information.)

3. Is the statement you linked publicly available / from the website or was it in an email? In the first case, please add the link to the official announcement (not only the picture; as the statement might change). In the latter one, please add a picture (which does not contain PII) to the PR in the folder vendor-statements. See [2Brightsparks](https://github.com/NCSC-NL/log4shell/blob/main/software/vendor-statements/2Brightsparks.png) as example.

If you have any question, just ask them :-)

2021-12-21 19:27 UTC, Securenetology commented on software/README.md
> +| Docvue | Docvue Client Agent | fix | Unknown | Unknown | Unknown | Unknown | New client package can be retrieved from support. | |
Thanks! I think I got it! Unfortunately, all they gave me was an email. I redacted some company information.

2021-12-22 10:18 UTC, tschmidtb51 commented on software/README.md
> +| Docvue | Docvue Client Agent | fix | Unknown | Unknown | Unknown | Unknown | New client package can be retrieved from support. | |
I see two problems here:
1. Unfortunately, your email does not mention which of the vulnerabilities was fixed nor the exact version.
2. It is currently unclear which one of the Docvue companies you meant. The best way to clarify that is to include the email address (at least the domain name) into the picture. See [2Brightsparks](https://github.com/NCSC-NL/log4shell/blob/main/software/vendor-statements/2Brightsparks.png) how it should look like.
3. (But that is not a problem as you can upload the picture together with your PR.) The picture is not located inside the PR.

2021-12-24 16:59 UTC, Securenetology commented
Vendor statement

![DV](https://user-images.githubusercontent.com/89155495/147365863-af6f478f-cf14-41b3-a07c-791e8f198bd1.png)

2021-12-24 17:07 UTC, Securenetology commented on software/README.md
> +| Docvue | Docvue Client Agent | fix | Unknown | Unknown | Unknown | Unknown | New client package can be retrieved from support. | |
Updated with vendor statement and added correct vendor.

2021-12-25 16:59 UTC, Securenetology commented on software/README.md
> +| Docvue | Docvue Client Agent | fix | Unknown | Unknown | Unknown | Unknown | New client package can be retrieved from support. | |
All fixed!

2021-12-27 10:13 UTC, tschmidtb51 requested changes
@Securenetology Thank you for your contribution.

I have a few remarks:
1. The name of the company seems to be `WolfePak`. Please adopt the name of the picture.
2. Please redact the names from the email addresses. (redacting anything before the @wolfepak.com)
3. Please redact the name from the starting "Copied on this email".
4. It is still unclear to me whether the fix is regarding the usage of Log4j 1.x or 2.x. Is there anyway you can clarify that?

2021-12-27 10:13 UTC, tschmidtb51 commented on software/README.md
> +| WolfPack Softwae | Docvue Client Agent and Server Agent | 11.1.6.10447 | Fix | Investigation | Investigation | Investigation | New client package can be retrieved from support. | [source](vendor-st
```suggestion
| WolfePak Software | Docvue Client Agent and Server Agent | 11.1.6.10447 | Fix | Investigation | Investigation | Investigation | New client package can be retrieved from support. | [source](vendor-statements/WolfPack-Docvue.png) |

2021-12-27 16:34 UTC, tschmidtb51 requested changes
@Securenetology  Thank you for your contribution.

Due to Github limits, we needed to reorganize the repo. Please close this PR and re-submit your changes.

The comments from this PR are still valid. Please address them in your new PR.

2022-01-24 10:47 UTC, dev-NCSC-NL commented
Last contact was 24 day's ago. I'm closing this one.

2022-01-24 10:47 UTC, closed without merging