Add Fedex Ship Manager
NCSC-NL/log4shell pull request #724
Opened 2021-12-21 18:11 UTC by Gadgetgeek2000

Updated Fedex Ship Manager to 3509, adding notes about pending 3510 update 1/24.

Thank you for your contribution! Some pointers to get it merged quickly:

For contributions in `software/`:

  - [ ] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
  - [ ] Status: please select a value from the status table at the top
  - [ ] Version: Status Vulnerable / Workaround? -> List vulnerable versions.
             Status Fix?                     -> List fixed versions.
  - [ ] Links: make sure you link to a public statement by the developer.
    Alternatively, include and link a file in the `software/vendor-statements/`
    directory
  - [ ] Please mind the sorting

2021-12-21 18:12 UTC, Gadgetgeek2000 commented
Hopefully the proposed change looks ok. Editing a table on the website using the pipes was rough.

2021-12-21 21:19 UTC, tschmidtb51 requested changes
@Gadgetgeek2000 Thank you for your contribution.

I have several remarks:
1. As log4j 2.17 is not that old, I guess 3509 uses 2.16 now. Therefore, CVE-2021-44228 and CVE-2021-45046 should list the status _Fix_.
2. I'm not 100% familiar what 1/24 means in terms of a release date
3. Please provide a source. I guess there is not official statement about that yet (as you used "direct msg to rep"). So please add a picture (*without any PII*) to the PR for the vendor-statements folder. See [2Brightsparks](https://github.com/NCSC-NL/log4shell/blob/main/software/vendor-statements/2Brightsparks.png) as example.

2021-12-21 21:37 UTC, Gadgetgeek2000 commented
I wish I were more familiar with Github and modifying. I believe the rep meant it was slated for release on 1/24/2022.  Yes, the software now includes 2.16.0, so "fix" sounds correct.

2021-12-21 21:44 UTC, Gadgetgeek2000 commented
I tried to upload the image but the folder is locked
![fedex ship manager](https://user-images.githubusercontent.com/5576809/147001475-3a11d1f1-f1dd-4d0f-9f8f-abd7d87d42ab.png)
.

2021-12-22 10:28 UTC, tschmidtb51 commented
> I tried to upload the image but the folder is locked 

I had a look and it seems like you forked it correctly. So you should be able to upload the picture if you go to https://github.com/Gadgetgeek2000/log4shell/tree/patch-1/software/vendor-statements and click upload file. If that is not possible, please post the error message here.
I currently can push to your repo so it seems that you did not allow maintainers to edit your PR. See [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for an explanation.

> ![fedex ship manager](https://user-images.githubusercontent.com/5576809/147001475-3a11d1f1-f1dd-4d0f-9f8f-abd7d87d42ab.png) .

Please include in the image the email address (at least the domain name) the statement was sent from. This helps other users to identify whether they look at the right company as company names can be quite similar.

2021-12-27 16:35 UTC, tschmidtb51 requested changes
@Gadgetgeek2000  Thank you for your contribution.

Due to Github limits, we needed to reorganize the repo. Please close this PR and re-submit your changes.

The comments from this PR are still valid. Please address them in your new PR.

2022-02-03 01:38 UTC, closed without merging