Update software_list_s.md
NCSC-NL/log4shell pull request #780
Opened 2021-12-27 17:02 UTC by anssi-cvp

Updated Stormshield with specific advisory for StormShield Visibility Center (only product announced vulnerable to CVE-2021-44228)
Updated SonicWall product list based on v2.3 of their advisory

Thank you for your contribution! Some pointers to get it merged quickly:

For contributions in `software/`:

  - [ ] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
  - [ ] Status: please select a value from the status table at the top
  - [ ] Version: Status Vulnerable / Workaround? -> List vulnerable versions.
             Status Fix?                     -> List fixed versions.
  - [ ] Links: make sure you link to a public statement by the developer.
    Alternatively, include and link a file in the `software/vendor-statements/`
    directory
  - [ ] Please mind the sorting

2021-12-27 18:28 UTC, tschmidtb51 commented
Just closing and reopening to trigger Github Actions.

2021-12-27 20:33 UTC, govgitty requested changes
hi @anssi-cvp , thanks for contributing to the software list. Can you have a look at my comments? Some changes are necessary before we can merge.

2021-12-27 20:33 UTC, govgitty commented on software/software_list_s.md
> +|SonicWall|CSCMA| |Not vuln|Not vuln|Not vuln|Not vuln|based on v2.3 of advisory|[source](https://psirt.global.sonicwall.com/vuln-detail/SNWLID-2021-0032)|
CVE-2021-4104 is not mentioned in the advisory.
```suggestion
|SonicWall|CSCMA| | |Not vuln|Not vuln|Not vuln|based on v2.3 of advisory|[source](https://psirt.global.sonicwall.com/vuln-detail/SNWLID-2021-0032)|

2021-12-27 20:33 UTC, govgitty commented on software/software_list_s.md
> +|SonicWall|Cloud Edge| |Not vuln|Not vuln|Not vuln|Not vuln|based on v2.3 of advisory|[source](https://psirt.global.sonicwall.com/vuln-detail/SNWLID-2021-0032)|
CVE-2021-4104 is not mentioned in the advisory.
```suggestion
|SonicWall|Cloud Edge| | |Not vuln|Not vuln|Not vuln|based on v2.3 of advisory|[source](https://psirt.global.sonicwall.com/vuln-detail/SNWLID-2021-0032)|

2021-12-27 20:33 UTC, govgitty commented on software/software_list_s.md
> +|SonicWall|Email Security|10.0.13|Not vuln|Fix|Fix|Fix|based on version 2.3 of advisory|[source](https://psirt.global.sonicwall.com/vuln-detail/SNWLID-2021-0032)|
CVE-2021-4104 is not mentioned in the advisory.
```suggestion
|SonicWall|Email Security|10.0.13| |Fix|Fix|Fix|based on version 2.3 of advisory|[source](https://psirt.global.sonicwall.com/vuln-detail/SNWLID-2021-0032)|

2021-12-27 20:33 UTC, govgitty commented on software/software_list_s.md
> +|SonicWall|EPRS| |Not vuln|Not vuln|Not vuln|Not vuln|based on version 2.3 of advisory|[source](https://psirt.global.sonicwall.com/vuln-detail/SNWLID-2021-0032)|
CVE-2021-4104 is not mentioned in the advisory.
```suggestion
|SonicWall|EPRS| | |Not vuln|Not vuln|Not vuln|based on version 2.3 of advisory|[source](https://psirt.global.sonicwall.com/vuln-detail/SNWLID-2021-0032)|

2021-12-27 20:33 UTC, govgitty commented on software/software_list_s.md
> +|SonicWall|NSM On-Premise|2.3.2-R12-H2|Not vuln|Fix|Fix|Fix|based on version 2.3 of advisory|[source](https://psirt.global.sonicwall.com/vuln-detail/SNWLID-2021-0032)|
CVE-2021-4104 is not mentioned in the advisory.
```suggestion
|SonicWall|NSM On-Premise|2.3.2-R12-H2| |Fix|Fix|Fix|based on version 2.3 of advisory|[source](https://psirt.global.sonicwall.com/vuln-detail/SNWLID-2021-0032)|

2021-12-28 08:49 UTC, anssi-cvp commented
Hello, the original line seems to have one separator more than expected. What do you prefer ? Should I cancel my PR and send it again after correcting this error or do you do it on your side ?

2021-12-28 13:53 UTC, govgitty commented
@anssi-cvp, thank you for your contribution.

2021-12-28 13:53 UTC, merged

2021-12-28 14:06 UTC, tschmidtb51 commented
> Hello, the original line seems to have one separator more than expected. What do you prefer ? Should I cancel my PR and send it again after correcting this error or do you do it on your side ?

@anssi-cvp You can always add commits to a Pull Request (to be precise: to the branch the PR is based on) to fix such issues by yourself. There is no need to cancel a PR if a check fails.