Added IBM Cognos Analytics
NCSC-NL/log4shell pull request #793
Opened 2021-12-28 12:43 UTC by stijnZCERT

Thank you for your contribution! Some pointers to get it merged quickly:

For contributions in `software/`:

  - [ ] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
  - [ ] Status: please select a value from the status table at the top
  - [ ] Version: Status Vulnerable / Workaround? -> List vulnerable versions.
             Status Fix?                     -> List fixed versions.
  - [ ] Links: make sure you link to a public statement by the developer.
    Alternatively, include and link a file in the `software/vendor-statements/`
    directory
  - [ ] Please mind the sorting

2021-12-28 14:28 UTC, certeu commented
Hello @stijnZCERT, thank you very much for contributing to the software list. Could you please have a look at my comments and see if they are valid?

2021-12-28 14:29 UTC, certeu requested changes

2021-12-28 14:29 UTC, certeu commented on software/software_list_i.md
> +| IBM | IBM Cognos Analytics | 11.2.x, 11.1.x, 11.0.6 to 11.0.13 | | Fix | Fix | | Versions 11.0.5 and earlier are not vulnerable | [source](https://www.ibm.com/blogs/psirt/security-bulletin-ibm-cogn
The listed versions seems to be the vulnerable ones while the status indicates `fix`.  I would suggest either to change the status by vulnerable or to change the versions to indicate the fixed ones (`11.2.1 Interim Fix 2`, `11.1.7 Interim Fix 7`, and `11.0.13 Interim Fix 4`)

Please, refer to this link https://www.ibm.com/support/pages/node/6528388 which seems to contain the most recent data about IBM Cognos Analytics

2021-12-29 10:20 UTC, stijnZCERT commented on software/software_list_i.md
> +| IBM | IBM Cognos Analytics | 11.2.x, 11.1.x, 11.0.6 to 11.0.13 | | Fix | Fix | | Versions 11.0.5 and earlier are not vulnerable | [source](https://www.ibm.com/blogs/psirt/security-bulletin-ibm-cogn
Thanks @certeu . I opened a new PR with the changes your recommended. Someone else added some IBM products to.

2021-12-29 10:21 UTC, closed without merging