updated VMware list and removed some duplicates
NCSC-NL/log4shell pull request #879
Opened 2022-01-28 11:57 UTC by Goldshop

Thank you for your contribution! Some pointers to get it merged quickly:

For contributions in `software/`:

  - [ ] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
  - [ ] Status: please select a value from the status table at the top
  - [ ] Version: Status Vulnerable / Workaround? -> List vulnerable versions.
             Status Fix?                     -> List fixed versions.
  - [ ] Links: make sure you link to a public statement by the developer.
    Alternatively, include and link a file in the `software/vendor-statements/`
    directory
  - [ ] Please mind the sorting

2022-01-29 19:50 UTC, tschmidtb51 requested changes
@Goldshop Thank you for your contribution.

Could you please a have a look at my comments? Some changes are necessary before we can merge.

2022-01-29 19:50 UTC, tschmidtb51 commented on software/software_list_v.md
> +|VMware|Identity Manager|patches for 3.3.5, 3.3.4, 3.3.3| Not vuln | Fix | Fix | Not vuln | |[VMSA-2021-0028.1 (vmware.com)](https://www.vmware.com/security/advisories/VMSA-2021-0028.html) [KB] (http
```suggestion
|VMware|Identity Manager|3.3.6| Not vuln | Fix | Fix | Not vuln | |[VMSA-2021-0028.1 (vmware.com)](https://www.vmware.com/security/advisories/VMSA-2021-0028.html) [KB] (https://kb.vmware.com/s/article/87185)|

2022-01-29 19:50 UTC, tschmidtb51 commented on software/software_list_v.md
> +|VMware|NSX-T Intelligence Appliance|1.2.x, 1.1.x| Not vuln |Fix|Fix| Not vuln | |[VMSA-2021-0028.1 (vmware.com)](https://www.vmware.com/security/advisories/VMSA-2021-0028.html)|
I didn't find that one. Did you mean?
```suggestion
|VMware|NSX Intelligence |1.2.1.1| Not vuln |Fix|Fix| Not vuln | |[VMSA-2021-0028.1 (vmware.com)](https://www.vmware.com/security/advisories/VMSA-2021-0028.html)|
```
If so, please adopt sorting.

2022-01-29 19:50 UTC, tschmidtb51 commented on software/software_list_v.md
> +|VMware|SD-WAN VCO|4.x| Not vuln | Fix | Fix | Not vuln | |[VMSA-2021-0028.1 (vmware.com)](https://www.vmware.com/security/advisories/VMSA-2021-0028.html) [fix](https://kb.vmware.com/s/article/87158)
|VMware|SD-WAN VCO|4.x| Not vuln | Fix | Fix | Not vuln | Check [KB 87158](https://kb.vmware.com/s/article/87158) for applicable builds|[VMSA-2021-0028.1 (vmware.com)](https://www.vmware.com/security/advisories/VMSA-2021-0028.html) [fix](https://kb.vmware.com/s/article/87158)|

2022-01-29 19:50 UTC, tschmidtb51 commented on software/software_list_v.md
> +|VMware|Smart Assurance M&R|6.8u5, 7.0u8, 7.2.0.1| Not vuln | Vulnerable | Vulnerable | Not vuln | |[VMSA-2021-0028.1 (vmware.com)](https://www.vmware.com/security/advisories/VMSA-2021-0028.html)|
```suggestion
|VMware|Smart Assurance M&R|6.8u5, 7.0u8, 7.2.0.1| Not vuln | Workaround | Workaround | Not vuln | |[VMSA-2021-0028.1 (vmware.com)](https://www.vmware.com/security/advisories/VMSA-2021-0028.html)|

2022-01-29 19:50 UTC, tschmidtb51 commented on software/software_list_v.md
>  |VMware|Smart Assurance NCM|10.1.6| | Vulnerable | Vulnerable | | |[VMSA-2021-0028.1 (vmware.com)](https://www.vmware.com/security/advisories/VMSA-2021-0028.html)|
```suggestion
|VMware|Smart Assurance NCM|10.1.6| Not vuln | Workaround | Workaround | | |[VMSA-2021-0028.1 (vmware.com)](https://www.vmware.com/security/advisories/VMSA-2021-0028.html)|

2022-01-29 19:50 UTC, tschmidtb51 commented on software/software_list_v.md
> +|VMware|Smart Assurance SAM [Service Assurance Manager]|10.1.0.x, 10.1.2, 10.1.5| Not vuln | Vulnerable | Vulnerable | Not vuln | |[VMSA-2021-0028.1 (vmware.com)](https://www.vmware.com/security/advi
```suggestion
|VMware|Smart Assurance SAM [Service Assurance Manager]|10.1.5.5 | Not vuln | Vulnerable | Vulnerable | Not vuln | |[VMSA-2021-0028.1 (vmware.com)](https://www.vmware.com/security/advisories/VMSA-2021-0028.html)|

2022-01-29 19:50 UTC, tschmidtb51 commented on software/software_list_v.md
> +|VMware|Tanzu Operations Manager|2.8.18, 2.9.25, 2.10.24| Not vuln | Fix | Fix | Not vuln | |[VMSA-2021-0028.1 (vmware.com)](https://www.vmware.com/security/advisories/VMSA-2021-0028.html)  [workarou
According to the second link:
```suggestion
|VMware|Tanzu Operations Manager|2.8.19, 2.9.26, 2.10.25| Not vuln | Fix | Fix | Fix | |[VMSA-2021-0028.1 (vmware.com)](https://www.vmware.com/security/advisories/VMSA-2021-0028.html) [workaround](https://community.pivotal.io/s/article/5004y00001mPn2N1639255611105?language=en_US) [fix](https://network.pivotal.io/products/ops-manager/)|

2022-01-29 19:50 UTC, tschmidtb51 commented on software/software_list_v.md
> +|VMware|Tanzu SQL with MySQL for VMs|2.x, 1.x| Not vuln |Not vuln|Not vuln | Not vuln | |[source](https://kb.vmware.com/s/article/87068)|
Does that only apply for version 2.x and 1.x or for all versions?

2022-01-29 19:50 UTC, tschmidtb51 commented on software/software_list_v.md
> +|VMware|Telco Cloud Automation|2.x, 1.x| Not vuln |Not vuln| Not vuln | Not vuln | |[source](https://kb.vmware.com/s/article/87068)|
Same question here.

2022-01-29 19:50 UTC, tschmidtb51 commented on software/software_list_v.md
> +|VMware|vCenter Server - OVA|6.x| Not vuln | Workaround | Workaround | Not vuln |<a href="https://kb.vmware.com/s/article/87081" rel="nofollow">Workaround @ KB87081 (vmware.com)</a>|[VMSA-2021-0028.4
```suggestion
|VMware|vCenter Server - OVA|6.x| Not vuln | Workaround | Workaround | Not vuln |[VMSA-2021-0028.4 (vmware.com)](https://www.vmware.com/security/advisories/VMSA-2021-0028.html) [Workaround](https://kb.vmware.com/s/article/87081)|

2022-01-29 19:50 UTC, tschmidtb51 commented on software/software_list_v.md
> +|VMware|vCenter Server - OVA|7.0U3c| Not vuln | Fix | Fix | Not vuln |<a href="https://kb.vmware.com/s/article/87081" rel="nofollow">Workaround @ KB87081 (vmware.com)</a>|[VMSA-2021-0028.4 (vmware.co
```suggestion
|VMware|vCenter Server - OVA|7.0U3c| Not vuln | Fix | Fix | Not vuln | |[VMSA-2021-0028.4 (vmware.com)](https://www.vmware.com/security/advisories/VMSA-2021-0028.html) [Workaround](https://kb.vmware.com/s/article/87081) [fix](https://docs.vmware.com/en/VMware-vSphere/7.0/rn/vsphere-vcenter-server-70u3c-release-notes.html)|

2022-01-29 19:50 UTC, tschmidtb51 commented on software/software_list_v.md
> +|VMware|vCenter Server - Windows|6.7.x, 6.5.x| Not vuln | Workaround | Workaround | Not vuln |<a href="https://kb.vmware.com/s/article/87096" rel="nofollow">Workaround @ KB87096 (vmware.com)</a>|[VMS
```suggestion
|VMware|vCenter Server - Windows|6.7.x, 6.5.x| Not vuln | Workaround | Workaround | Not vuln | |[VMSA-2021-0028.4 (vmware.com)](https://www.vmware.com/security/advisories/VMSA-2021-0028.html) [Workaround](https://kb.vmware.com/s/article/87096)|

2022-01-29 19:50 UTC, tschmidtb51 commented on software/software_list_v.md
> +|VMware|vRealize Network Insight|5.3, 6.x| Not vuln | Vulnerable | Vulnerable | Not vuln | |[VMSA-2021-0028.1 (vmware.com)](https://www.vmware.com/security/advisories/VMSA-2021-0028.html)|
```suggestion
|VMware|vRealize Network Insight|6.5| Not vuln | Fix | Fix | Not vuln | |[VMSA-2021-0028.1 (vmware.com)](https://www.vmware.com/security/advisories/VMSA-2021-0028.html)|

2022-01-30 21:29 UTC, Goldshop commented
All changes have been completed

2022-01-31 21:57 UTC, tschmidtb51 approved these changes
Thank you for your contribution.

2022-01-31 21:57 UTC, merged